version: "3.8"
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    env_file:
      - .env.n8n
    volumes:
      - n8n_data:/home/node/.n8n

  automation-assistant:
    build: .
    env_file: .env
    depends_on:
      - n8n

volumes:
  n8n_data:
